disabled_rules:
  - line_length
  - type_name
  - file_length
  - identifier_name

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - Sources
  - Tests
  - Examples

function_body_length:
  warning: 50
